### ISSUE TITLE
Noobie question how to install this?

### ISSUE THREAD

**Issue by woodsbox** [chrome-php/headless-chromium-php#8] opened 2018-04-25 15:05 UTC
Hi guys,

So I have a apache with php 7 installed on a Ubuntu VPS.
I installed the library to the html directory of apache and created a php page.
On the page I have: require 'vendor/autoload.php';
After that the example code of the installation page.
I get the error:

Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed in /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:326 Stack trace: #0 /var/www/html/vendor/chrome-php/chrome/src/Utils.php(51): HeadlessChromium\Browser\BrowserProcess->HeadlessChromium\Browser\{closure}(Object(Symfony\Component\Process\Process)) #1 /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(361): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator)) #2 /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(124): HeadlessChromium\Browser\BrowserProcess->waitForStartup(Object(Symfony\Component\Process\Process), 30000000) #3 /var/www/html/vendor/chrome-php/chrome/src/BrowserFactory.php(59): HeadlessChromium\Browser\BrowserProcess->start('chrome', Array) #4 /var/www/html/index.php(16): HeadlessChromium\BrowserFactory->createBrowser() #5 {main} thrown in /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php on line 326

Any idea what to do?

**Comment by gsouf** [comment] 2018-04-25 15:33
Hi @woodsbox are chrome binaries installed on you machine?

**Comment by woodsbox** [comment] 2018-04-25 17:37
Hi @gsouf  do you have a good manual to install the chrome binaries? Let me check that if I have everything installed. Probably not!

**Comment by gsouf** [comment] 2018-04-25 17:54
I guess that on ubuntu you can simply do: ``sudo apt-get install chromium-browser``

If you use chromium-browser you will probably want to [specify the chrome executable](https://github.com/chrome-php/headless-chromium-php#using-different-chrome-executable)

**Comment by woodsbox** [comment] 2018-04-25 17:59
chromium-browser is installed. When I do: chromium-browser

I get the message:

[15049:15049:0425/175723.610418:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

But I think that is not the problem when I open the php page because that will not do it under the user root right?

**Comment by gsouf** [comment] 2018-04-25 18:00
Yes php wont run it as root. Additionnally the library uses chrome in no-sandbox mode, so even if you would run as root it would work.

**Comment by woodsbox** [comment] 2018-04-25 18:03
So again:
- chromium-browser is installed 
- I installed the chrome-php into the html folder of apache
- I have the following php page:
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require 'vendor/autoload.php';
use HeadlessChromium\BrowserFactory;
$browserFactory = new BrowserFactory();
// starts headless chrome
$browser = $browserFactory->createBrowser();
// creates a new page and navigate to an url
$page = $browser->createPage();
$page->navigate('http://www.google.com')->waitForNavigation();
// get page title
$pageTitle = $page->evaluate('document.title')->getReturnValue();
$browser->close();
echo $pageTitle;
?>

**Comment by gsouf** [comment] 2018-04-25 18:03
Sorry, no the previous statement was wrong. ``no-sandbox`` is not added. So you need to make sure you wont run your php scripts as root, that anyway I wont recommend

**Comment by woodsbox** [comment] 2018-04-25 18:04
the php script will be run as www-data user i guess

**Comment by woodsbox** [comment] 2018-04-25 18:06
Pressed the wrong button I closed it 😄

**Comment by gsouf** [comment] 2018-04-25 18:12
Is it working now? If it does, that's ok, feel free to close the issue.

Just a side note, when you copy paste code sample you can use 3 backquotes (```) instead of 1 in order to format a block of code.

**Comment by woodsbox** [comment] 2018-04-25 18:13
no not working still


Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed in /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php:326 Stack trace: #0 /var/www/html/vendor/chrome-php/chrome/src/Utils.php(51): HeadlessChromium\Browser\BrowserProcess->HeadlessChromium\Browser\{closure}(Object(Symfony\Component\Process\Process)) #1 /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(361): HeadlessChromium\Utils::tryWithTimeout(30000000, Object(Generator)) #2 /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(124): HeadlessChromium\Browser\BrowserProcess->waitForStartup(Object(Symfony\Component\Process\Process), 30000000) #3 /var/www/html/vendor/chrome-php/chrome/src/BrowserFactory.php(59): HeadlessChromium\Browser\BrowserProcess->start('chrome', Array) #4 /var/www/html/index.php(16): HeadlessChromium\BrowserFactory->createBrowser() #5 {main} thrown in /var/www/html/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php on line 326

**Comment by gsouf** [comment] 2018-04-25 18:17
Ok, can you please add some debug options on the factory:

```php
 $browser = $browserFactory->createBrowser([
      'debugLogger'     => 'php://stdout'
 ]);
```

This will provide additional information that will help to understand why it fails.

**Comment by woodsbox** [comment] 2018-04-25 18:27
of topic question would it be possible to open a page fill a form and submit the form?

**Comment by gsouf** [comment] 2018-04-25 18:44
Yes it is.

When you call ``$page->evaluate($code);``  what you pass via ``$code`` is javascript code that will be evaluated in the browser context.

Quick example: 

```php
$page
    ->evaluate(
        '(() => {
            document.querySelector('#myinput').value = 'hello';
            document.querySelector('#myform').submit();
        })()'
    )
    ->getReturnValue();
```

However the library might not be able to detect navigation initiated from the page and you might have some issues to wait for the new page to load. If you have issues concerning this feel free to open a new ticket. That's anyway something the library will have to handle.

**Closed** 2018-04-25 18:58 UTC
Labels: help wanted

**Comment by danielloynaz** [comment] 2018-07-12 21:18
Hi, 
I'm having the same issue on Windows 10. 
I'm executing the following code: 
`$browserFactory = new BrowserFactory('C:\Program Files (x86)\Google\Chrome\Application\chrome');

        // starts headless chrome
        $browser = $browserFactory->createBrowser([
            'debugLogger' => 'php://stdout'
        ]);

        // creates a new page and navigate to an url
        $page = $browser->createPage();
        $page->navigate('http://localhost/testingprintpdf/')->waitForNavigation();

        // get page title
        $pageTitle = $page->evaluate('document.title')->getReturnValue();
        
        // bye
        $browser->close();

        echo $pageTitle;`

and I get this error:

> Fatal error: Uncaught RuntimeException: Cannot read chrome version, make sure you provided the correct chrome executable using: "C:\Program Files (x86)\Google\Chrome\Application\chrome". in C:\xampp\htdocs\TestingPrintPDF\vendor\chrome-php\chrome\src\BrowserFactory.php on line 103

**Comment by gsouf** [comment] 2018-07-13 10:12
Hi @danielloynaz 

I'm not a windows pro, but what if you add `.exe` at the end? Like this:

```
 $browserFactory = new BrowserFactory('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe');
 ```

**Comment by danielloynaz** [comment] 2018-07-13 18:17
Hi @gsouf ,

I have tried with/without ".exe", added the chrome's binary folder to the variable Path in the environment and I have tested using Chrome and Chromium.
I think, I'm missing something.

**Comment by gsouf** [comment] 2018-07-14 07:48
When you open a command line and if you type `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` does it open chrome?

**Comment by danielloynaz** [comment] 2018-07-17 16:17
Yes, chrome open by typing  `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`  
Using `$browserFactory->createBrowser(['debugLogger' => 'php://stdout']);` I get this error: 

> Fatal error: Uncaught RuntimeException: Cannot read chrome version, make sure you provided the correct chrome executable using: "C:\Program Files (x86)\Google\Chrome\Application\chrome". in C:\xampp\htdocs\TestingPrintPDF\vendor\chrome-php\chrome\src\BrowserFactory.php on line 103

and with `$browserFactory->createBrowser();`  I get this other:

> Fatal error: Uncaught RuntimeException: Chrome process stopped before startup completed.

**Comment by danielloynaz** [comment] 2018-07-17 18:22
I have tried with the same process on Linux. This time I get this error

> PHP Fatal error:  Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (3sec) in /home/xxxxxxx/generatepdf/vendor/chrome-php/chrome/src/Utils.php:65
Stack trace:
#0 /home/xxxxxxx/generatepdf/vendor/chrome-php/chrome/src/Communication/ResponseReader.php(103): HeadlessChromium\Utils::tryWithTimeout(3000000, Object(Generator))
#1 /home/xxxxxxx/generatepdf/vendor/chrome-php/chrome/src/Communication/Session.php(78): HeadlessChromium\Communication\ResponseReader->waitForResponse(3000)
#2 /home/xxxxxxx/generatepdf/vendor/chrome-php/chrome/src/Browser.php(113): HeadlessChromium\Communication\Session->sendMessageSync(Object(HeadlessChromium\Communication\Message))
#3 /home/xxxxxxx/generatepdf/export.php(13): HeadlessChromium\Browser->createPage()
#4 {main}
  thrown in /home/xxxxxxx/generatepdf/vendor/chrome-php/chrome/src/Utils.php on line 65

**Comment by Necklaces** [comment] 2018-09-05 05:37
Hi, I'm trying to use this library, but 4 out of 5 times I get the same "HeadlessChromium\Exception\OperationTimedOut: Operation timed out" error as danielloynaz. I've tried to turn off headless to see what it does, and it'll create a browser with an initial browserpage, then open a new tab and 4 out of 5 times it won't navigate to the specified link..

**Comment by woodsbox** [comment] 2018-09-05 06:38
Hi @Necklaces can you show your code?

**Comment by Necklaces** [comment] 2018-09-05 07:12
Sorry for wasting your time, found another solution using puppeteer that works for me.

**Comment by gsouf** [comment] 2018-09-05 07:37
@Necklaces can you still provide a code sample to reproduce your issue please?

**Comment by Necklaces** [comment] 2018-09-05 07:44
It's literally just the example in the readme. I'm guessing it's related to my environment or something, I have chromium and a fork of chromium called iridium installed on Arch GNU/Linux.

**Comment by gsouf** [comment] 2018-09-05 07:48
@Necklaces ok thank you. Did you notice it to bit a little bit slow to execute with puppeteer? 

Maybe some operations take time to complete in your env and I suspect the default timeout to bit loo low.

**Comment by Necklaces** [comment] 2018-09-05 08:06
No, if anything it seems faster, but I might be wrong. I also tried setting timeout using this library with the `$navigation->waitForNavigation(Page::DOM_CONTENT_LOADED, 10000)` option, but the error is from the `createPage` function, as seen in danielloynaz' paste, so I don't think it even got there.

**Comment by gsouf** [comment] 2018-09-05 08:26
There is a timeout for create page as well. I will investigate. Thanks for the details

**Comment by dczaretsky** [comment] 2018-11-02 20:16
I'm running on CentOS with PHP 7. I saw this same error and was able to fix it by increasing the sync time from 3 to 5 secs.

```
$factory = new BrowserFactory('chromium-browser');
$browser = $factory->createBrowser([
      'debugLogger' => 'php://stdout',
      'sendSyncDefaultTimeout' => 5000,
]);
```

However, now I'm getting a different runtime error in Centos. From what I can see, it looks as though Chrome is trying to create a directory called .local in the /var/ww/html root directory, which is bad. I've tried to set other directories using the commands userDataDir but that doesn't effect anything. Anyone have a way around this bug? 

`PHP Fatal error:  Uncaught RuntimeException: Chrome process stopped before startup completed. Additional info: mkdir: cannot create directory '/.local': Permission denied\ntouch: cannot touch '/.local/share/applications/mimeapps.list': No such file or directory\nFailed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted\n[1102/200937.790939:FATAL:zygote_host_impl_linux.cc(198)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid). \n#0 0x7f60d4321ece base::debug::StackTrace::StackTrace()\n#1 0x7f60d428686c logging::LogMessage::~LogMessage()\n#2 0x7f60be33552a service_manager::ZygoteHostImpl::LaunchZygote()\n#3 0x7f60cd4b054e content::(anonymous namespace)::LaunchZygoteHelper()\n#4 0x7f60be3343f3 service_manager::ZygoteCommunication::Init()\n#5 0x7f60be33adb9 service_manager::CreateGenericZygote()\n#6 0x7f60cd4afac1 content::ContentMainRunnerImpl::Initialize()\n#7 0x7f60d45e1908 service_manager::Main()\n#8 0x7f60cd4adbf5 in /var/www/html/libraries/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php on line 381
`

**Comment by gsouf** [comment] 2018-11-02 20:46
@dczaretsky can show what value you use for ``userDataDir ``, the whole code snippet please

**Comment by dczaretsky** [comment] 2018-11-02 21:38
I've tried:
'userDataDir' => '/var/www/private/tmp',
'userDataDir' => '/var/www/html/tmp',

Both directories have the proper write permissions. I've run on the command line with no problems. For example:
sudo -u apache php test.php

The program executes correctly on the commandline but fails using the browser.

**Comment by gsouf** [comment] 2018-11-02 21:50
If it works on cli, but not with from apache it's most likely that there is an issue of configuration somewhere in machine. To me it does not look it's something that comes from library

**Comment by dczaretsky** [comment] 2018-11-02 22:05
If I go to noSandbox mode, it causes a fatal error -- it seems to time out with another error:

`Fatal error: Uncaught HeadlessChromium\Exception\OperationTimedOut: Operation timed out (5sec) in /var/www/html/libraries/vendor/chrome-php/chrome/src/Utils.php:65 Stack trace: #0 /var/www/html/libraries/vendor/chrome-php/chrome/src/Communication/ResponseReader.php(103): HeadlessChromium\Utils::tryWithTimeout(5000000, Object(Generator)) #1 /var/www/html/libraries/vendor/chrome-php/chrome/src/Communication/Session.php(79): HeadlessChromium\Communication\ResponseReader->waitForResponse(5000) #2 /var/www/html/libraries/vendor/chrome-php/chrome/src/Browser.php(129): HeadlessChromium\Communication\Session->sendMessageSync(Object(HeadlessChromium\Communication\Message)) #3 /var/www/html/meta.php(29): HeadlessChromium\Browser->createPage() #4 {main} thrown in /var/www/html/libraries/vendor/chrome-php/chrome/src/Utils.php on line 65
`

Here is the Debug log:

[```
2018-11-02 22:01:35] DEBUG Factory: chrome version: Chromium 68.0.3440.106 Fedora Project
[2018-11-02 22:01:35] DEBUG process: initializing
[2018-11-02 22:01:35] DEBUG process: using directory: /var/www/private/tmp
[2018-11-02 22:01:35] DEBUG process: starting process: chromium-browser --remote-debugging-port=0 --disable-background-networking --disable-background-timer-throttling --disable-client-side-phishing-detec
tion --disable-default-apps --disable-extensions --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --saf
ebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --headless --disable-gpu --hide-scrollbars --mute-audio --no-sandbox --user-data-dir=/var/www/private/tmp
[2018-11-02 22:01:35] DEBUG process: waiting for 30 seconds for startup
[2018-11-02 22:01:35] DEBUG process: chrome output:mkdir: cannot create directory '/.local': Permission denied
touch: cannot touch '/.local/share/applications/mimeapps.list': No such file or directory
[2018-11-02 22:01:35] DEBUG process: ignoring output:mkdir: cannot create directory '/.local': Permission denied
[2018-11-02 22:01:35] DEBUG process: ignoring output:touch: cannot touch '/.local/share/applications/mimeapps.list': No such file or directory
[2018-11-02 22:01:37] DEBUG process: chrome output:[1102/220137.058403:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.
[2018-11-02 22:01:37] DEBUG process: ignoring output:[1102/220137.058403:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.
[2018-11-02 22:01:37] DEBUG process: chrome output:Home directory not accessible: Permission denied

DevTools listening on ws://127.0.0.1:36537/devtools/browser/37a0cdce-decf-498e-9720-24f91ff7043e
[1102/220137.079149:ERROR:udev_linux.cc(21)] Failed to initialize udev, possibly due to an invalid system configuration. Various device-related browser features may be broken.
[2018-11-02 22:01:37] DEBUG process: ignoring output:Home directory not accessible: Permission denied
[2018-11-02 22:01:37] DEBUG process: ✓ accepted output
[2018-11-02 22:01:37] DEBUG process: connecting using ws://127.0.0.1:36537/devtools/browser/37a0cdce-decf-498e-9720-24f91ff7043e
[2018-11-02 22:01:37] DEBUG socket(1): connecting
[2018-11-02 22:01:37] DEBUG socket(1): ✓ connected
[2018-11-02 22:01:37] DEBUG socket(1): → sending data:{"id":1,"method":"Target.setDiscoverTargets","params":{"discover":true}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"63FFC3699E19DEC24820A7587316615B","type":"page","title":"","url":"about:blank","attached":false,"browserContextId":"6DFC564E83BB2939BA2C76DC6F690F79"}}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"84c0471c-6162-4c81-84f7-67489cb45391","type":"browser","title":"","url":"","attached":false}}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"928945ce-72cd-4a6e-85fa-94cd22beeb11","type":"browser","title":"","url":"","attached":true}}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"id":1,"result":{}}
[2018-11-02 22:01:37] DEBUG connection: ⇶ dispatching method:Target.targetCreated
[2018-11-02 22:01:37] DEBUG connection: ⇶ dispatching method:Target.targetCreated
[2018-11-02 22:01:37] DEBUG connection: ⇶ dispatching method:Target.targetCreated
[2018-11-02 22:01:37] DEBUG socket(1): → sending data:{"id":2,"method":"Target.createTarget","params":{"url":"about:blank"}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"987D75A58443F0B77F538E94C7B513DE","type":"page","title":"","url":"","attached":false,"browserContextId":"6DFC564E83BB2939BA2C76DC6F690F79"}}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"id":2,"result":{"targetId":"987D75A58443F0B77F538E94C7B513DE"}}
[2018-11-02 22:01:37] DEBUG connection: ⇶ dispatching method:Target.targetCreated
[2018-11-02 22:01:37] DEBUG socket(1): → sending data:{"id":3,"method":"Target.attachToTarget","params":{"targetId":"987D75A58443F0B77F538E94C7B513DE"}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"987D75A58443F0B77F538E94C7B513DE","type":"page","title":"","url":"about:blank","attached":true,"browserContextId":"6DFC564E83BB2939BA2C76DC6F690F79"}}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"method":"Target.attachedToTarget","params":{"sessionId":"987D75A58443F0B77F538E94C7B513DE:1","targetInfo":{"targetId":"987D75A58443F0B77F538E94C7B513DE","type":"page","title":"","url":"about:blank","attached":true,"browserContextId":"6DFC564E83BB2939BA2C76DC6F690F79"},"waitingForDebugger":false}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"id":3,"result":{"sessionId":"987D75A58443F0B77F538E94C7B513DE:1"}}
[2018-11-02 22:01:37] DEBUG connection: ⇶ dispatching method:Target.targetInfoChanged
[2018-11-02 22:01:37] DEBUG connection: ⇶ dispatching method:Target.attachedToTarget
[2018-11-02 22:01:37] DEBUG socket(1): → sending data:{"id":5,"method":"Target.sendMessageToTarget","params":{"message":"{\"id\":4,\"method\":\"Page.getFrameTree\",\"params\":[]}","sessionId":"987D75A58443F0B77F538E94C7B513DE:1"}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"id":5,"result":{}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"63FFC3699E19DEC24820A7587316615B","type":"page","title":"","url":"about:blank","attached":false,"browserContextId":"6DFC564E83BB2939BA2C76DC6F690F79"}}}
[2018-11-02 22:01:37] DEBUG connection: ⇶ dispatching method:Target.targetInfoChanged
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"987D75A58443F0B77F538E94C7B513DE","type":"page","title":"","url":"about:blank","attached":true,"browserContextId":"6DFC564E83BB2939BA2C76DC6F690F79"}}}
[2018-11-02 22:01:37] DEBUG socket(1): ← receiving data:{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"987D75A58443F0B77F538E94C7B513DE:1","message":"{\"method\":\"Inspector.targetCrashed\",\"params\":{}}","targetId":"987D75A58443F0B77F538E94C7B513DE"}}
[2018-11-02 22:01:37] DEBUG connection: ⇶ dispatching method:Target.targetInfoChanged
[2018-11-02 22:01:37] DEBUG session(987D75A58443F0B77F538E94C7B513DE:1): ⇶ dispatching method:Inspector.targetCrashed
[2018-11-02 22:01:42] DEBUG process: killing chrome
[2018-11-02 22:01:42] DEBUG process: trying to close chrome gracefully
[2018-11-02 22:01:42] DEBUG socket(1): → sending data:{"id":6,"method":"Browser.close","params":[]}
[2018-11-02 22:01:42] DEBUG socket(1): ← receiving data:{"id":6,"result":{}}
[2018-11-02 22:01:42] DEBUG socket(1): disconnecting
[2018-11-02 22:01:42] DEBUG socket(1): ✓ disconnected
[2018-11-02 22:01:42] DEBUG process: waiting for process to close

```

**Comment by gsouf** [comment] 2018-11-02 22:19
Replace value ``/var/www/private/tmp`` with ``/var/www/private/tmp/chromeData``

**Comment by dczaretsky** [comment] 2018-11-02 23:50
I'm not sure why that would matter, but no it didn't make a difference.

**Comment by dczaretsky** [comment] 2018-11-03 12:10
With regards to the mkdir error, I'm a bit lost. I did some research on the chrome code, and found that it uses the HOME env variable  for the .local directory path.

In my example.php file, I've set up the following command:
putenv('HOME=/var/www/private/tmp');

This seems to work when I run: `sudo -u apache php example.php`   
I can see that the files and directories are properly stored the in the /var/www/private/tmp directory. But again, running it through apache did not take the HOME env variable. I tried to set the env `HOME=/var/www/private/tmp` in the apache config file under `/etc/sysconfig/httpd` and that had no impact. I also tried passing in the --homedir parameter as described here: https://peter.sh/experiments/chromium-command-line-switches/#homedir

Any other thoughts on how to make chrome-php work with apache on centos?

**Comment by gsouf** [comment] 2018-11-04 10:14
``putenv('HOME=/var/www/private/tmp');`` will just change your env for php runtime, not for your machine, it's expected that chrome won't use it. 

I keep saying that it's an issue with your environment. You should find how to set env variable for the apache user's environment, not for php. 

https://httpd.apache.org/docs/2.4/env.html

**Comment by dczaretsky** [comment] 2018-11-05 05:10
Right, using SetEnv in the apache conf file solved the problem with writing the data to the proper directory. However, I'm still seeing these errors causing chrome to crash:

[2018-11-03 13:20:02] DEBUG process: chrome output:Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[2018-11-03 13:20:02] DEBUG process: ignoring output:Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

Any idea why this is happening?

**Comment by dczaretsky** [comment] 2018-11-06 00:50
Turns out this was a problem with the Selinux configuratio on my Centos server.  Selinux is preventing chrome-sandbox from accessing certain processes, which I discovered in the audit.log.

For anyone else having this problem, I solved it by generate a local policy module to allow access, as follows:

```
sudo ausearch -c 'chrome' --raw | audit2allow -M chrome_audit
semodule -i chrome_audit.pp

```
