### ISSUE TITLE
Page::getHtml() undefined?

### ISSUE THREAD

**Issue by rcoenen** [chrome-php/headless-chromium-php#194] opened 2021-02-10 06:06 UTC
Windows 10 / 64 bit
PHP 7.4.9 (cli) (built: Aug 4 2020 11:51:50) ( NTS Visual C++ 2017 x64 )
Chrome Version 88.0.4324.150 (Official Build) (64-bit)

WORKS:
$output_png = __DIR__ . '/output.png';
$page->screenshot()->saveToFile($output_png);

FAILS:
 $html = $page->getHtml();

Fatal error: Uncaught Error: Call to undefined method HeadlessChromium\Page::getHtml() in C:\wamp64\www\myproject\test_chrome_01.php on line 51

**Comment by GrahamCampbell** [comment] 2021-02-10 08:59
Duplicate of https://github.com/chrome-php/headless-chromium-php/issues/188. :)

**Closed as completed by GrahamCampbell** 2021-02-10 08:59 UTC
