### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jaskolek** [chrome-php/headless-chromium-php#68] opened 2019-02-14 18:14 UTC
Hi, first of all, thank you for your work on this lib!

I found some bug in the code. Basically, when I create a long script that goes to many pages, I'm running out of memory.
You can reproduce it simply with code like this:

```
$browserFactory = new BrowserFactory('google-chrome');
$browser = $browserFactory->createBrowser();
$page = $browser->createPage();
for($i = 0; $i < 100; ++$i){
    page->navigate('https://www.google.pl')->waitForNavigation();
    var_dump(memory_get_usage());
}
```

You will see that it uses more and more memory.

I found that the problem is with the wrench library and this solves the problem:
https://github.com/varspool/Wrench/pull/121/commits/6257a25ca5e23233533e2462250478d8d7841634
But this includes changing the library code. Is there any other way to fix this without changing the libraries code?

**Comment by johnanthonyeletto** [comment] 2019-02-15 00:22
Same problem here

**Comment by johnanthonyeletto** [comment] 2019-02-15 01:03
@jaskolek Good find with the wrench library! We should get that fix into here. Here is my workaround for now. 

1. Uninstall chrome-php/chrome from your project
```composer remove chrome-php/chrome```

2. Download the ***chrome-php/chrome*** source and bring it into your project.

3. Modify the composer.json in the ***chrome-php/chrome*** source to include wrench ~3.0.
```
"require": {
    "php": ">=7.0",
    "symfony/process": "^3|^4",
    "wrench/wrench": "~3.0",
    "symfony/filesystem": "^3|^4",
    "psr/log": "^1.0",
    "apix/log": "^1.2",
    "evenement/evenement": "^3.0.1"
  },
```

4. Link ***chrome-php/chrome*** in ***your project's*** composer.json.
```
"repositories": [
        {
            "type": "path",
            "url": "./path/to/chrome-php"
        }
    ]
```

5. Install ***chrome-php/chrome*** using composer.
``` composer require chrome-php/chrome @dev ```

6. Watch your memory usage stay nice and low.

Hope this helps! I was going crazy trying to optimize my code.

**Comment by t-geindre** [comment] 2019-02-24 17:05
@johnanthonyeletto 
A simpler solution is to use the composer `as` feature. Add the following line in your `composer.json` :
```json
{
  "require": {
    "wrench/wrench": "dev-master as 2.0.0"
  }
}
```
Then run `composer update wrench/wrench`, this will install the latest version of Wrench and still satisfy dependencies requirements.

**Comment by t-geindre** [comment] 2019-02-25 09:33
@johnanthonyeletto  A simpler solution is to use the composer `as` feature. Add the following line in your `composer.json` :
```json
{
  "require": {
    "wrench/wrench": "dev-master as 2.0.0"
  }
}
```
Then run `composer update wrench/wrench`, this will install the latest version of Wrench and still satisfy dependencies requirements.

Same issue here btw.

**Comment by gsouf** [comment] 2019-03-06 10:40
Thanks for your investigation. 👍
I'll be looking into that issue

**Comment by t-geindre** [comment] 2019-03-13 15:32
Is anyone aware of another possible memory leak issue ?
After updating wrench/wrench, the memory usage of my application is still increasing.
I'm not sure where the problem comes from, just asking.

**Comment by DangerLifter** [comment] 2019-06-12 10:33
After update wrench/wrench to dev memory usage keep to increase slower. About 2Mb per 2 pages. Single browser and single page in it are used.

**Comment by t-geindre** [comment] 2019-06-13 09:02
Same issue here.
But not sure if it's related to the lib or my own code.

**Comment by p1ho** [comment] 2019-07-02 18:57
@t-geindre Thanks for the composer.json code, it's a vast improvement even if it doesn't solve it completely!
For me, the memory increases at about .02MB for single browser single page. Which is significantly better than before I applied the change.

**Comment by WindBridges** [comment] 2020-07-29 22:04
I don't know what is exactly happened, but today after updating Windows 10 (developing under Ubuntu WSL), chrome-php begins to work very slowly, freezing on each CDP request. I figured out that it works fast when I install wrench 2.0.0 back, but freezes again on dev-master. Keeping version 2.0 means return back to memory leaks, but it doesn't work with dev-master normally from today. Any ideas?

**Comment by horror** [comment] 2020-10-21 23:54
> @t-geindre Thanks for the composer.json code, it's a vast improvement even if it doesn't solve it completely!
> For me, the memory increases at about .02MB for single browser single page. Which is significantly better than before I applied the change.

Same. Please fix it. I almost broke my head when I caught exceptions from symfony process component (used by chrome-php/headless-chromium-php) with "Unable to launch a new process". Only after hours of debugging i get "proc_open(): fork failed - Cannot allocate memory" and i able to find this issue. This is terrible

**Comment by anderson-comvex** [comment] 2021-02-19 15:16
This should not be staled and it is still an issue. Even after updating the `wrench/wrench` when used on the `php artisan queue:work` in daemon mode.

**Comment by GrahamCampbell** [comment] 2021-02-19 17:37
Since the problem is with the upstream library, I am closing this.

**Closed** 2021-02-19 17:37 UTC
Labels: to do
