### ISSUE TITLE
Accessing iframe elements

### ISSUE THREAD

**Issue by ethaniel** [chrome-php/headless-chromium-php#442] opened 2022-10-11 10:26 UTC
Hello!

A page that I am loading contains an iframe. I couldn't find a way to search/click on elements inside that iframe.
The iframe contains a captcha checkbox, which when clicked loads a modal box with a captcha image and form which I am trying to parse.

Any ideas how to approach this without blindly clicking on a specific x/y offset?

**Comment by ethaniel** [comment] 2022-10-11 15:23
If somebody else stumbles open this issue, I managed to find a workaround:
```php
// check if element exists within an iframe
$count = $page->evaluate(
'(() => {
	var iframe = document.getElementById("random-iframe");
	var elmnt = iframe.contentWindow.document.body.getElementsByClassName("random-element").length;
	return elmnt;
})()'
)->getReturnValue();
```
```php
// click on an element within an iframe
$page->evaluate(
'(() => {
	var iframe = document.getElementById("random-iframe");
	iframe.contentWindow.document.body.getElementsByClassName("random-element")[0].click();
})()'
)->getReturnValue();
```
```php
// get image src from an element within an iframe
$image = $page->evaluate(
'(() => {
	var iframe = document.getElementById("random-iframe");
	return iframe.contentWindow.document.body.getElementsByClassName("random-image")[0].src;
})()'
)->getReturnValue();

```

**Comment by enricodias** [comment] 2022-10-11 19:24
You are essentially using pure javascript to do what you need. The `Dom` class has search and click functions that doesn't rely on javascript, but we don't have a way to change the context to a specific iframe yet.

I'll leave this issue closed since it's a duplicate of #371, but this feature can be implemented in the future.

**Closed as completed by enricodias** 2022-10-11 19:24 UTC

**Comment by remco-pc** [comment] 2023-09-06 19:31
Does this also work cross origin if not which flag should i use, i saw selenium has a iframe Support for this, cors could be disabled in the browser with a flag?

**Comment by shawn996** [comment] 2024-04-11 08:27
```
    public function contentFrame(): ?self
    {
        $message = new Message('DOM.describeNode', [
            'nodeId' => $this->nodeId,
        ]);
        $response = $this->page->getSession()->sendMessageSync($message);

        $this->assertNotError($response);

        $node = $response->getResultData('node');
        if (null !== $node && 0 !== $node) {
            return new self($this->page, $node['contentDocument']['nodeId']);
        }

        return null;
    }
```
node.php add function on abave

$iframes=$page->dom()->search('//iframe');
$iframes[0]->contentFrame();
