### ISSUE TITLE
Connection refused port 6000

### ISSUE THREAD

**Issue by kaistaerk** [chrome-php/headless-chromium-php#116] opened 2019-11-11 09:39 UTC
Hi,

in my local dev env it works well. On my production system it fails.

Error message in shell:
```
connect 127.0.0.1 port 6000: Connection refused
connect 127.0.0.1 port 6000: Connection refused
connect 127.0.0.1 port 6000: Connection refused
connect 127.0.0.1 port 6000: Connection refused
.....
```

```
$browserFactory = new BrowserFactory('/usr/bin/google-chrome');

// starts headless chrome
$browser = $browserFactory->createBrowser([
    'noSandbox' => true
]);

// creates a new page and navigate to an url
$page = $browser->createPage();
$page->navigate('https://www.google.de/')->waitForNavigation();
$page->screenshot()->saveToFile('test.png');

// bye
$browser->close();
```

Any ideas what is going wrong here? Firewall is accepting any connection

Thx, Regards,
Kai

**Comment by gsouf** [comment] 2020-02-28 19:16
Apologize for the delay. I would say the port 6000 is already taken on the server. Are you still looking for a fix?

**Comment by gsouf** [comment] 2020-04-10 13:28
I'll assume the issue is fixed and I'm closing it. Please feel free to re-open if you're still experiencing it.

**Closed by gsouf** 2020-04-10 13:28 UTC
